name: CI

on: [push]

env:
  AWS_SECRET_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, World
    - name: Run multiple line script
      run: |
        echo Add other actions to build
        echo $AWS_SECRET_ACCESS_KEY_ID
