name: CI

on: [push]

env:
  ID: ID
  ARTIFACT_NAME: hello.yml
jobs:
  build:
    if: github.ref_name=='main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, World
    - name: Run multiple line script
      run: |
        echo Add other actions to build
        echo $AWS_SECRET_ACCESS_KEY_ID
        printenv
        
  artifact-upload:
    name: Upload code artifact
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/upload-artifact@v3.1.2
      with: 
        name: ${{ env.ARTIFACT_NAME }}
        path: ./.github/workflows
  deploy:
    name: "Deploy infrastructure"
    runs-on: ubuntu-latest
    steps:
      - name: "Set environment variable"
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          MY_VARIABLE: "my value"
        run: |
          echo $MY_VARIABLE
      - name: "Checkout the code"
        uses: actions/checkout@v2
