name: CD
on: push
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: Surious96/cool-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: FIXED
